### PR TITLE
Change icon app name

### PR DESCRIPTION
**Pull request by jdrichards50**
Change from "ChartIQ" to "ChartIQ Demo"

Test this by deploying locally against an emulator/real device and check the name under the icon on the mobile home page.

### CODE REVIEW

**Comment by samuel-ciq** [comment]
A few questions:

1. On my copy of the app that I downloaded from the app store the text just says "Demo". Do you know why this is different from what I'm seeing in the emulator? Based on your change here I would expect it so say "ChartIQ" instead. 

2. I suppose it's not possible to tell android not to truncate the name? 
image

3. When I open up App Info I get this: 
image

Should this also say ChartIQ Demo?

**Comment by jdrichards50** [comment]
> A few questions:
> 
> 1. On my copy of the app that I downloaded from the app store the text just says "Demo". Do you know why this is different from what I'm seeing in the emulator? Based on your change here I would expect it so say "ChartIQ" instead.
> 2. I suppose it's not possible to tell android not to truncate the name?
>    image
> 3. When I open up App Info I get this:
>    image
> 
> Should this also say ChartIQ Demo?

No, nothing we can do about the name truncation. The app was deployed with the name "Demo", which is why you see that on the downloaded app. "ChartIQ" never made it to deployment.

**Comment by samuel-ciq** [comment]
Okay cool. Do you know what's going on with 3? I'm seeing that in the branch here. Worth worry about?

**Comment by jdrichards50** [comment]
> Okay cool. Do you know what's going on with 3? I'm seeing that in the branch here. Worth worry about?

I'm seeing "ChartIQ Demo" for the app info on my emulator. Are you looking at the emulator or deploying on a real device. If it's a real device you might have to uninstall the existing app. If on a emulator you might want to do a clean build.

**Comment by samuel-ciq** [comment]
I tried cleaning, uninstalling, and invalidating and nothing seemed to work. But then I downloaded the Pixel 3 image instead of the Pixel 2 one Android Studio comes with and it's showing up properly there so ¯\_(ツ)_/¯

**Review by samuel-ciq — APPROVED** [review]

**Pull request merged**
